//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestruture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencias
    {
        public int ID_Incidencias { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaIncidencia { get; set; }
        public string EstadoSolicitud { get; set; }
        public string EstadoActual { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
