//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestruture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanCobro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanCobro()
        {
            this.EstadoCuenta = new HashSet<EstadoCuenta>();
            this.RubroCobro = new HashSet<RubroCobro>();
        }
    
        public int ID_PlanCobro { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> TotalPrecioRubro { get; set; }
        public string EstadoActual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadoCuenta> EstadoCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RubroCobro> RubroCobro { get; set; }
    }
}
