//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestruture.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ReservacionData))]
    public partial class Reservacion
    {
        public int ID_Reservacion { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public Nullable<int> ID_AreaComun { get; set; }
        public string Confirmacion { get; set; }
        public Nullable<System.DateTime> Dia { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFinal { get; set; }
    
        public virtual AreaComun AreaComun { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
