//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestruture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Residencia()
        {
            this.EstadoCuenta = new HashSet<EstadoCuenta>();
        }
    
        public int ID_Residencia { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public string NumeroResidencia { get; set; }
        public Nullable<int> CantidadPersonas { get; set; }
        public Nullable<System.DateTime> AnnoInicio { get; set; }
        public Nullable<int> CantidadAutos { get; set; }
        public string EstadoResidencia { get; set; }
        public string EstadoActual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadoCuenta> EstadoCuenta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
